language: julia

os:
  - linux
  - osx

sudo: false

julia:
  - 0.6
  - 0.7
  - nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

after_success:
  - julia -e 'include(Pkg.dir("DocStringExtensions", "test", "coverage.jl"))'

jobs:
  include:
    - stage: "Deploy docs"
      julia: 0.6
      os: linux
      script: julia -e 'Pkg.add("Documenter"); Pkg.checkout("Documenter")'
        && julia ${TRAVIS_BUILD_DIR}/docs/make.jl
      after_success: skip
