site_name:        DocStringExtensions.jl
repo_url:         https://github.com/JuliaDocs/DocStringExtensions.jl
site_description: DocString extensions for Julia.
site_author:      Michael Hatherly

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - fenced_code
  - admonition

docs_dir: 'build'

pages:
- Home: index.md
